# Generated by Django 4.2.24 on 2025-09-09 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default='sin_imagen/', upload_to='inmuebles/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(default='default-profile.webp', upload_to='foto_perfil/'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='arrendatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
