# Generated by Django 4.2.24 on 2025-09-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_inmueble_imagen_perfilusuario_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='comuna',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='comuna_codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='comuna_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='region_codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='region_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
