# Generated by Django 4.2.24 on 2025-09-17 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_inmueble_comuna_inmueble_comuna_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'permissions': [('gestionar_comuna', 'Puede gestionar comunas')]},
        ),
        migrations.AlterModelOptions(
            name='inmueble',
            options={'permissions': [('gestionar_inmueble', 'Puede gestionar inmuebles'), ('ver_todos_inmuebles', 'Puede ver todos los inmuebles'), ('publicar_inmueble', 'Puede publicar inmuebles')]},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'permissions': [('gestionar_usuario', 'Puede gestionar usuarios'), ('ver_todos_usuarios', 'Puede ver todos los usuarios')]},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'permissions': [('gestionar_region', 'Puede gestionar regiones')]},
        ),
        migrations.AlterModelOptions(
            name='solicitudarriendo',
            options={'permissions': [('gestionar_solicitud', 'Puede gestionar solicitudes de arriendo'), ('aprobar_solicitud', 'Puede aprobar/rechazar solicitudes')]},
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ARRENDADOR', 'Arrendador'), ('ARRENDATARIO', 'Arrendatario'), ('ADMINISTRADOR', 'Administrador')], default='ARRENDATARIO', max_length=13),
        ),
    ]
