# Generated by Django 4.2.23 on 2025-08-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_solicitudarriendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarriendo',
            name='mensaje',
            field=models.TextField(blank=True, default=''),
        ),
    ]
