# Generated by Django 4.2.24 on 2025-09-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_comuna_options_alter_inmueble_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='esta_publicado',
            field=models.BooleanField(default=False),
        ),
    ]
