# Generated by Django 4.2.24 on 2025-09-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_inmueble_esta_publicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inmuebles/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='portal.inmueble')),
            ],
            options={
                'ordering': ['orden', 'creado'],
            },
        ),
    ]
