# Generated by Django 4.2.24 on 2025-09-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_inmueble_esta_publicado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmueble',
            options={'permissions': [('agregar_inmueble', 'Puede agregar inmuebles'), ('editar_propio_inmueble', 'Puede editar sus propios inmuebles'), ('eliminar_propio_inmueble', 'Puede eliminar sus propios inmuebles'), ('ver_todos_inmuebles', 'Puede ver todos los inmuebles'), ('editar_todos_inmuebles', 'Puede editar todos los inmuebles'), ('eliminar_todos_inmuebles', 'Puede eliminar todos los inmuebles'), ('publicar_inmueble', 'Puede publicar/despublicar inmuebles')]},
        ),
    ]
