# Generated by Django 4.2.24 on 2025-09-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_inmueble_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='comuna_codigo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Comuna'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='region_codigo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Región'),
        ),
    ]
