# Generated by Django 4.2.24 on 2025-10-01 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_inmueble_comuna_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='m2_construidos',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='m2_totales',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual',
            field=models.PositiveIntegerField(help_text='Precio mensual en pesos chilenos', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
