# Generated by Django 4.2.25 on 2025-10-02 18:59

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_inmueble_m2_construidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default='inmuebles/sin_imagen.jpg', upload_to=portal.models.Inmueble.upload_to_inmuebles),
        ),
    ]
