# Generated by Django 4.2.25 on 2025-10-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_perfilusuario_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='comuna_codigo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de Comuna'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='region_codigo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de Región'),
        ),
    ]
